
#FROM node:16-alpine as build
FROM node:lts-alpine
WORKDIR /app
COPY package.json .
#RUN npm set timeout=1000000
RUN npm install
COPY . .
CMD npm run build

FROM nginx:latest
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80